all:
	g++ -fopenmp -Iinclude src/options.cpp src/count.cpp src/main.cpp -o post_pred_check.out -O3
debug:
	g++ -fopenmp -Iinclude src/options.cpp src/count.cpp src/main.cpp -o post_pred_check.out -g
clean:
	rm *.out
