all:
	g++ -fopenmp -Iinclude src/options.cpp src/count.cpp src/main.cpp -o edge_test.out -O3
debug:
	g++ -fopenmp -Iinclude src/options.cpp src/count.cpp src/main.cpp -o edge_test.out -g
clean:
	rm *.out
